# reproduction for yaml's structure

model:
  image_size: 256
  num_channels: 256 # default 256
  num_res_blocks: 2
  channel_mult: ""
  learn_sigma: true
  class_cond: False
  use_checkpoint: False
  use_scale_shift_norm: True
  dropout: 0.0
  resblock_updown: true
  use_fp16: false
  # 注意力机制相关参数
  num_heads: 4
  num_head_channels: 64
  num_heads_upsample: -1
  attention_resolutions: "32,16,8"
  use_new_attention_order: false

diffusion:
  steps: 1000
  learn_sigma: true
  sigma_small: False
  noise_schedule: "linear"
  use_kl: False
  predict_xstart: False
  rescale_timesteps: false
  rescale_learned_sigmas: false
  timestep_respacing: "250"

classifier:
  image_size: 256
  classifier_use_fp16: false
  classifier_width: 128
  classifier_depth: 2
  classifier_attention_resolutions: "32,16,8"
  classifier_use_scale_shift_norm: true
  classifier_resblock_updown: true
  classifier_pool: attention

sampling:
  clip_denoised: True
  show_progress: true
  num_samples: 100
  use_ddim: False
  model_path: ./data/pretrained/celeba256_250000.pt
  name: template
  fix_seed: False
  process_xt: true
  process_xstart: true
  # 仅在条件生成时使用的参数
  classifier_scale: 4.0
  classifier_path: ""

schedule_jump_params:
  t_T: 250
  n_sample: 1
  jump_length: 10
  jump_n_sample: 10
  add_noise_once: true

schedule_jump_params2:
  t_T: 250 # 总步数
  jump_length: 10 # 每次回跳多少步
  jump_sapcing: 10 # 每隔多少步进行一次回跳
  jump_n_sample: 10
  add_noise_once: false
  jump_start_pct: 0.04 # 从 T 的 xx% 开始考虑回跳
  jump_stop_pct: 1.0 # 到 T 的 xx% 停止考虑回跳

data:
  eval:
    paper_face_mask:
      mask_loader: true
      gt_path: ./data/datasets/gts-old1/face
      mask_path: ./data/datasets/gt_keep_masks-old1/face
      image_size: 256
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 1
      return_dataloader: true
      offset: 0
      max_len: 8
      paths:
        srs: ./log/face_example2/inpainted_xt
        srx: ./log/face_example2/inpainted_xstart
        lrs: ./log/face_example2/gt_masked
        gts: ./log/face_example2/gt
        gt_keep_masks: ./log/face_example2/gt_keep_mask
